image: node:latest
stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script: npm test
  artifacts:
    paths:
      - allure-results